# Generated by Django 4.2.5 on 2023-09-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Hygienist',
        ),
    ]
